# Generated by Django 2.2.6 on 2019-10-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trail',
            options={'verbose_name_plural': 'trails'},
        ),
    ]
