# Generated by Django 2.2.6 on 2019-10-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0002_auto_20191026_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='difficulty',
            field=models.IntegerField(choices=[(0, ' '), (1, 'Bardzo łatwa'), (2, 'Łatwa'), (3, 'Średnio trudna'), (4, 'Dla wytrwałych'), (5, 'Mega')]),
        ),
    ]
