# Generated by Django 2.2.6 on 2019-10-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0003_auto_20191027_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
