# Generated by Django 2.2.6 on 2019-10-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0004_auto_20191027_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
